project_id = "wquzijmkiotkupygoxdf"

[functions.generate-cosmic-profile]
verify_jwt = false

[functions.discover-profiles]
verify_jwt = false

[functions.generate-icebreaker]
verify_jwt = false

[functions.generate-weekly-insights]
verify_jwt = false

[functions.generate-daily-intention]
verify_jwt = false

[functions.push-vapid-key]
verify_jwt = false

[functions.who-liked-me]
verify_jwt = false
