import CosmicBackground from "@/components/CosmicBackground";
import { Card, CardContent } from "@/components/ui/card";
import { ShieldAlert } from "lucide-react";
import Footer from "@/components/Footer";

const Disclaimer = () => {
  return (
    <div className="min-h-screen bg-background relative">
      <CosmicBackground />
      {/* pb-24 keeps the last paragraph clear of the mobile bottom tab bar. */}
      <div className="relative z-10 pt-20 pb-24 md:pb-12">
        <div className="max-w-3xl mx-auto px-6">
          <div className="text-center mb-8">
            <ShieldAlert className="w-12 h-12 text-accent mx-auto mb-4" />
            <h1 className="text-3xl font-bold mb-2 text-foreground">
              Disclaimer &amp; Terms of Use
            </h1>
            <p className="text-muted-foreground">Last updated: April 2026</p>
          </div>

          <Card className="bg-card/80 backdrop-blur-sm border-border/50">
            <CardContent className="p-6 sm:p-8 space-y-6 text-sm leading-relaxed text-muted-foreground">

              <section>
                <h2 className="text-lg font-semibold text-foreground mb-2">1. No Responsibility for Meetups</h2>
                <p>
                  Stellara is a platform that facilitates online introductions only. We do not organize, supervise, or take any responsibility for in-person meetings between users. Any decision to meet another user in person is made entirely at your own risk. We strongly encourage users to meet in public places, inform a trusted friend or family member, and exercise caution.
                </p>
              </section>

              <section>
                <h2 className="text-lg font-semibold text-foreground mb-2">2. User-Shared Information</h2>
                <p>
                  You are solely responsible for the information you choose to share on your profile or in messages. Stellara is not liable for any consequences resulting from personal data, contact details, location, or other sensitive information that you voluntarily disclose to other users. We strongly advise against sharing financial information, home addresses, or other highly sensitive data through this platform.
                </p>
              </section>

              <section>
                <h2 className="text-lg font-semibold text-foreground mb-2">3. No Guarantee of Compatibility</h2>
                <p>
                  All astrological, Human Design, Gene Keys, and numerological readings are generated by AI for entertainment and self-exploration purposes only. Compatibility scores and cosmic profiles are not scientifically validated and should not be relied upon as the sole basis for relationship decisions. We make no warranties regarding the accuracy or predictive value of any cosmic, astrological, or spiritual content.
                </p>
              </section>

              <section>
                <h2 className="text-lg font-semibold text-foreground mb-2">4. User Conduct</h2>
                <p>
                  Users are expected to interact respectfully. Stellara is not responsible for the behavior, statements, or actions of any user on or off the platform. We reserve the right to remove accounts that engage in harassment, fraud, misrepresentation, or any conduct that violates community standards.
                </p>
              </section>

              <section>
                <h2 className="text-lg font-semibold text-foreground mb-2">5. Limitation of Liability</h2>
                <p>
                  To the fullest extent permitted by applicable law, Stellara and its creators, operators, affiliates, and partners shall not be held liable for any direct, indirect, incidental, consequential, or punitive damages arising from: (a) your use or inability to use the platform; (b) any interactions with other users, whether online or offline; (c) unauthorized access to your data; (d) reliance on any content, including AI-generated cosmic profiles; or (e) any other matter relating to the service.
                </p>
              </section>

              <section>
                <h2 className="text-lg font-semibold text-foreground mb-2">6. Privacy &amp; Data</h2>
                <p>
                  We collect and process personal data including birth data, preferences, and messaging content to provide our services. While we implement reasonable security measures, no system is 100% secure. By using Stellara, you acknowledge and accept the inherent risks of sharing personal information online. We do not sell your personal data to third parties.
                </p>
              </section>

              <section>
                <h2 className="text-lg font-semibold text-foreground mb-2">7. Age Requirement</h2>
                <p>
                  You must be at least 18 years of age to use this platform. By creating an account, you confirm that you are 18 or older.
                </p>
              </section>

              <section>
                <h2 className="text-lg font-semibold text-foreground mb-2">8. Indemnification</h2>
                <p>
                  You agree to indemnify and hold harmless Stellara and its operators from any claims, damages, losses, or expenses (including legal fees) arising from your use of the platform, your interactions with other users, or your violation of these terms.
                </p>
              </section>

              <section>
                <h2 className="text-lg font-semibold text-foreground mb-2">9. Modifications</h2>
                <p>
                  We reserve the right to update this disclaimer at any time. Continued use of the platform after changes constitutes acceptance of the revised terms.
                </p>
              </section>

              <section className="border-t border-border pt-4 mt-6">
                <p className="text-xs text-muted-foreground/70 text-center">
                  By using Stellara, you acknowledge that you have read, understood, and agree to be bound by this disclaimer. If you do not agree, please discontinue use of the platform.
                </p>
              </section>
            </CardContent>
          </Card>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default Disclaimer;
