import CosmicBackground from "@/components/CosmicBackground";
import { Card, CardContent } from "@/components/ui/card";
import { FileText } from "lucide-react";
import Footer from "@/components/Footer";

const TermsOfService = () => (
  <div className="min-h-screen bg-background relative">
    <CosmicBackground />
    <div className="relative z-10 pt-20 pb-12">
      <div className="max-w-3xl mx-auto px-6">
        <div className="text-center mb-8">
          <FileText className="w-12 h-12 text-accent mx-auto mb-4" />
          <h1 className="text-3xl font-bold mb-2 text-foreground">Terms of Service</h1>
          <p className="text-muted-foreground">Last updated: March 2026</p>
        </div>

        <Card className="bg-card/80 backdrop-blur-sm border-border/50">
          <CardContent className="p-6 sm:p-8 space-y-6 text-sm leading-relaxed text-muted-foreground">
            <section>
              <h2 className="text-lg font-semibold text-foreground mb-2">1. Acceptance of Terms</h2>
              <p>By accessing or using Stellara, you agree to be bound by these Terms of Service. If you do not agree, please do not use the platform.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-foreground mb-2">2. Eligibility</h2>
              <p>You must be at least 18 years old and legally able to enter into binding contracts. By creating an account, you represent and warrant that you meet these requirements.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-foreground mb-2">3. Account Responsibilities</h2>
              <p>You are responsible for maintaining the security of your account credentials. You must provide accurate and truthful information. You may not create multiple accounts, impersonate others, or use the platform for commercial purposes without authorization.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-foreground mb-2">4. Acceptable Use</h2>
              <p>You agree not to: harass, bully, or threaten other users; post illegal, harmful, or offensive content; use automated systems to access the platform; attempt to circumvent security measures; or engage in any activity that violates local, state, or federal laws.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-foreground mb-2">5. Content Ownership</h2>
              <p>You retain ownership of content you post. By posting, you grant Stellara a non-exclusive, worldwide, royalty-free license to use, display, and distribute your content in connection with the platform's services.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-foreground mb-2">6. Premium Subscriptions</h2>
              <p>Premium features are offered on a subscription basis. Payments are processed through Stripe. Subscriptions auto-renew unless cancelled. Refunds are handled according to the applicable app store's policy.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-foreground mb-2">7. AI-Generated Content</h2>
              <p>Cosmic profiles, compatibility scores, and insights are generated by artificial intelligence for entertainment and self-exploration purposes only. They should not be relied upon as professional advice of any kind.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-foreground mb-2">8. Termination</h2>
              <p>We may suspend or terminate your account at our discretion for violations of these terms. You may delete your account at any time through the Settings page, which will permanently remove all your data.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-foreground mb-2">9. Limitation of Liability</h2>
              <p>To the maximum extent permitted by law, Stellara shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the platform.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-foreground mb-2">10. Governing Law</h2>
              <p>These terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law principles.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-foreground mb-2">11. Contact Us</h2>
              <p>For questions about these Terms of Service, contact us at <a href="mailto:stellaradating@gmail.com" className="text-primary hover:underline">stellaradating@gmail.com</a>.</p>
            </section>

            <section className="border-t border-border pt-4 mt-6">
              <p className="text-xs text-muted-foreground/70 text-center">
                By using Stellara, you acknowledge that you have read, understood, and agree to these Terms of Service.
              </p>
            </section>
          </CardContent>
        </Card>
      </div>
      <Footer />
    </div>
  </div>
);

export default TermsOfService;
