// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-my-blueprint.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_blueprint_default = defineTool({
  name: "get_my_blueprint",
  title: "Get my cosmic blueprint",
  description: "Return the signed-in Stellara user's cosmic blueprint: astrology placements (sun/moon/rising/venus/mars/mercury), Human Design (type/authority/profile), and numerology (life path, personal year).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await client(ctx).from("profiles").select(
      "display_name,sun_sign,moon_sign,rising_sign,venus_sign,mars_sign,mercury_sign,human_design_type,human_design_authority,human_design_profile,life_path_number,personal_year_number,gene_keys_life_purpose,astro_summary,human_design_summary,numerology_summary"
    ).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: "No blueprint found \u2014 complete onboarding in Stellara first." }]
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { blueprint: data }
    };
  }
});

// src/lib/mcp/tools/get-today-briefing.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_today_briefing_default = defineTool2({
  name: "get_today_briefing",
  title: "Get today's cosmic briefing",
  description: "Return the signed-in user's most recent daily cosmic briefing from Stellara: energy theme, focus, mood, affirmation, cosmic weather, lucky window, and journal prompt.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await client2(ctx).from("daily_briefings").select("briefing_date,energy_theme,focus,mood,affirmation,cosmic_weather,lucky_window,journal_prompt").eq("user_id", ctx.getUserId()).order("briefing_date", { ascending: false }).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No briefing yet \u2014 open Stellara today to generate one." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { briefing: data }
    };
  }
});

// src/lib/mcp/tools/list-shadow-journal.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_shadow_journal_default = defineTool3({
  name: "list_shadow_journal_entries",
  title: "List shadow journal entries",
  description: "List the signed-in user's most recent Stellara shadow journal entries (prompt + entry text, newest first).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max entries to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await client3(ctx).from("shadow_journal_entries").select("id,prompt,entry,created_at,updated_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-shadow-journal.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function client4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_shadow_journal_default = defineTool4({
  name: "create_shadow_journal_entry",
  title: "Create a shadow journal entry",
  description: "Save a new shadow journal entry (prompt + reflection) for the signed-in user in Stellara.",
  inputSchema: {
    prompt: z2.string().trim().min(1).describe("The shadow work prompt being reflected on."),
    entry: z2.string().trim().min(1).describe("The user's written reflection.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ prompt, entry }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await client4(ctx).from("shadow_journal_entries").insert({ user_id: ctx.getUserId(), prompt, entry }).select("id,prompt,entry,created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved shadow entry ${data.id}` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/tools/list-moon-journal.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function client5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_moon_journal_default = defineTool5({
  name: "list_moon_journal_entries",
  title: "List moon journal entries",
  description: "List the signed-in user's most recent Stellara moon journal entries (phase, entry_type, content, newest first).",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Max entries to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await client5(ctx).from("moon_journal_entries").select("id,phase,entry_type,content,created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-moon-journal.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
function client6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_moon_journal_default = defineTool6({
  name: "create_moon_journal_entry",
  title: "Create a moon journal entry",
  description: "Save a new moon journal entry (moon phase, entry type, and content) for the signed-in Stellara user.",
  inputSchema: {
    phase: z4.string().trim().min(1).describe("Moon phase, e.g. 'New Moon', 'Waxing Crescent', 'Full Moon'."),
    entry_type: z4.string().trim().min(1).describe("Type of entry, e.g. 'intention', 'release', 'gratitude', 'reflection'."),
    content: z4.string().trim().min(1).describe("The entry content.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ phase, entry_type, content }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await client6(ctx).from("moon_journal_entries").insert({ user_id: ctx.getUserId(), phase, entry_type, content }).select("id,phase,entry_type,content,created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved moon entry ${data.id}` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wquzijmkiotkupygoxdf";
var mcp_default = defineMcp({
  name: "stellara-mcp",
  title: "Stellara",
  version: "0.1.0",
  instructions: "Stellara is a cosmic self-discovery app (astrology, Human Design, numerology, journaling). Use `get_my_blueprint` to read the user's cosmic placements, `get_today_briefing` for today's guidance, and the shadow/moon journal tools to read or add reflections. All tools act as the signed-in Stellara user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_my_blueprint_default,
    get_today_briefing_default,
    list_shadow_journal_default,
    create_shadow_journal_default,
    list_moon_journal_default,
    create_moon_journal_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
